---
- name: Create a user with sudo privileges
  hosts: all
  become: yes
  tasks:
    - name: Create a new user
      user:
        name: ansible  # Replace with desired username
        password: "{{ 'GDjzN3t5JUdWQXekSFHAYgs7'}}"  # Replace 'your_password' with the actual password
        shell: /bin/bash
        state: present

    - name: Add user to sudo group
      user:
        name: username  # Replace with the same username
        groups: sudo  # On Debian/Ubuntu; for CentOS/RHEL, use 'wheel'
        append: yes