---
- name: Remove Ansible user
  hosts: all
  become: yes
  tasks:
    - name: remove user ansible
      user:
        name: ansible  # Replace with desired username
        state: absent
        remove: true