---
- name: Update all AZC components
- hosts: all

  become: true
  tasks:
    - name: Update and Upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400

- include: update-azcauth.yaml

- include: update-realm1.yaml

- include: update-realm2.yaml

- include: update-realm3.yaml

- include: update-realm4.yaml