- hosts: azcauth

  become: true
  tasks:
    #- name: Update Auth
      shell: cd /azcore/azerothcore && git pull

    #- name: clean Build
      shell: rm -rf /azcore/azerothcore/build && mkdir /azcore/azerothcore/build

    #- name: new Build
      shell: cd /azcore/azerothcore/build && cmake ../ -DCMAKE_INSTALL_PREFIX=/azcore/azerothcore/env/dist/ -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DWITH_WARNINGS=1 -DTOOLS_BUILD=all -DSCRIPTS=static -DMODULES=static

    #- name: make Build
      shell: cd /azcore/azerothcore/build && make -j 4 && make install

    #- name: Reboot
      reboot:
        reboot_timeout: 3600

    #- name: Wait for reconnect
      wait_for_connection:
        connect_timeout: 10
        sleep: 5
        delay: 5
        timeout: 3600