- hosts: all

  become: true
  tasks:
    - name: open Realm1
      shell: cd /realms/realm1/azerothcore

    - name: update repo
      shell: git pull

    - name: update mod-autobalance
      shell: cd /realms/realm1/azerothcore/modules/mod-autobalance
      
    - name: update repo
      shell: git pull

    - name: update mod-eluna
      shell: cd /realms/realm1/azerothcore/modules/mod-eluna

    - name: update repo
      shell: git pull

    - name: update mod-individual-progression
      shell: cd /realms/realm1/azerothcore/modules/mod-individual-progression
    
    - name: update repo
      shell: git pull

    - name: update mod-npc-enchanter
      shell: cd /realms/realm1/azerothcore/modules/mod-npc-enchanter
    
    - name: update repo
      shell: git pull

    - name: update mod-ptr-template
      shell: cd /realms/realm1/azerothcore/modules/mod-ptr-template
    
    - name: update repo
      shell: git pull

    - name: move to Build
      shell: cd /realms/realm1/azerothcore/build

    - name: new Build
      shell: cmake ../ -DCMAKE_INSTALL_PREFIX=/realms/realm1/azerothcore/env/dist/ -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DWITH_WARNINGS=1 -DTOOLS_BUILD=all -DSCRIPTS=static -DMODULES=static

    - name: make Build
      shell: make -j 8 && make install

    - name: Reboot
      shell: reboot