---
- name: Update all AZC components
- hosts: all

  become: true
  tasks:
    - name: Update and Upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400

- name: Update Auth
- hosts: azcauth

  become: true
  tasks:
    - name: Update Auth
      shell: cd /azcore/azerothcore && git pull

    - name: clean Build
      shell: rm -rf /azcore/azerothcore/build && mkdir /azcore/azerothcore/build

    - name: new Build
      shell: cd /azcore/azerothcore/build && cmake ../ -DCMAKE_INSTALL_PREFIX=/azcore/azerothcore/env/dist/ -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DWITH_WARNINGS=1 -DTOOLS_BUILD=all -DSCRIPTS=static -DMODULES=static

    - name: make Build
      shell: cd /azcore/azerothcore/build && make -j 4 && make install

    - name: Reboot
      reboot:
        reboot_timeout: 3600

    - name: Wait for reconnect
      wait_for_connection:
        connect_timeout: 10
        sleep: 5
        delay: 5
        timeout: 3600

- name: update Realm1
- hosts: realm1

  become: true
  tasks:
    - name: Update Realm1
      shell: cd /realms/realm1/azerothcore && git pull

    - name: update mod-autobalance
      shell: cd /realms/realm1/azerothcore/modules/mod-autobalance && git pull

    - name: update mod-eluna
      shell: cd /realms/realm1/azerothcore/modules/mod-eluna && git pull

    - name: update mod-individual-progression
      shell: cd /realms/realm1/azerothcore/modules/mod-individual-progression && git pull

    - name: update mod-npc-enchanter
      shell: cd /realms/realm1/azerothcore/modules/mod-npc-enchanter && git pull

    - name: update mod-ptr-template
      shell: cd /realms/realm1/azerothcore/modules/mod-ptr-template && git pull

    - name: clean Build
      shell: rm -rf /realms/realm1/azerothcore/build && mkdir /realms/realm1/azerothcore/build

    - name: new Build
      shell: cd /realms/realm1/azerothcore/build && cmake ../ -DCMAKE_INSTALL_PREFIX=/realms/realm1/azerothcore/env/dist/ -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DWITH_WARNINGS=1 -DTOOLS_BUILD=all -DSCRIPTS=static -DMODULES=static

    - name: make Build
      shell: cd /realms/realm1/azerothcore/build && make -j 8 && make install

    - name: Reboot
      reboot:
        reboot_timeout: 3600

    - name: Wait for reconnect
      wait_for_connection:
        connect_timeout: 10
        sleep: 5
        delay: 5
        timeout: 3600        

- name: update Realm2
- hosts: realm2

  become: true
  tasks:
    - name: Update Realm2
      shell: cd /realms/realm2/azerothcore-wotlk && git pull

    - name: update mod-autobalance
      shell: cd /realms/realm2/azerothcore-wotlk/modules/mod-autobalance && git pull

    - name: update mod-individual-progression
      shell: cd /realms/realm2/azerothcore-wotlk/modules/mod-individual-progression && git pull

    - name: update mod-npc-enchanter
      shell: cd /realms/realm2/azerothcore-wotlk/modules/mod-npc-enchanter && git pull

    - name: update mod-playerbots
      shell: cd /realms/realm2/azerothcore-wotlk/modules/mod-playerbots && git pull

    - name: update mod-reagent-bank
      shell: cd /realms/realm2/azerothcore-wotlk/modules/mod-reagent-bank && git pull

    - name: update mod-solo-lfg
      shell: cd /realms/realm2/azerothcore-wotlk/modules/mod-solo-lfg && git pull

    - name: clean Build
      shell: rm -rf /realms/realm2/azerothcore-wotlk/build && mkdir /realms/realm2/azerothcore-wotlk/build

    - name: new Build
      shell: cd /realms/realm2/azerothcore-wotlk/build && cmake ../ -DCMAKE_INSTALL_PREFIX=/realms/realm2/azerothcore-wotlk/env/dist/ -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DWITH_WARNINGS=1 -DTOOLS_BUILD=all -DSCRIPTS=static -DMODULES=static

    - name: make Build
      shell: cd /realms/realm2/azerothcore-wotlk/build && make -j 8 && make install

    - name: Reboot
      reboot:
        reboot_timeout: 3600

    - name: Wait for reconnect
      wait_for_connection:
        connect_timeout: 10
        sleep: 5
        delay: 5
        timeout: 3600

- name: update Realm3
- hosts: realm3

  become: true
  tasks:
    - name: Update Realm3
      shell: cd /realms/realm3/busypvp && git pull

    - name: update mod-individual-progression
      shell: cd /realms/realm3/busypvp/modules/mod-individual-progression && git pull

    - name: update mod-npc-enchanter
      shell: cd /realms/realm3/busypvp/modules/mod-npc-enchanter && git pull

    - name: update mod-playerbots
      shell: cd /realms/realm3/busypvp/modules/mod-playerbots && git pull

    - name: clean Build
      shell: rm -rf /realms/realm3/busypvp/build && mkdir /realms/realm3/busypvp/build

    - name: new Build
      shell: cd /realms/realm3/busypvp/build && cmake ../ -DCMAKE_INSTALL_PREFIX=/realms/realm3/busypvp/env/dist/ -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DWITH_WARNINGS=1 -DTOOLS_BUILD=all -DSCRIPTS=static -DMODULES=static

    - name: make Build
      shell: cd /realms/realm3/busypvp/build && make -j 8 && make install

    - name: Reboot
      reboot:
        reboot_timeout: 3600

    - name: Wait for reconnect
      wait_for_connection:
        connect_timeout: 10
        sleep: 5
        delay: 5
        timeout: 3600

- name: update Realm4
- hosts: realm4

  become: true
  tasks:
    - name: Update Realm4
      shell: cd /realms/realm4/busyrp && git pull

    - name: update mod-individual-progression
      shell: cd /realms/realm4/busyrp/modules/mod-individual-progression && git pull

    - name: update mod-npc-enchanter
      shell: cd /realms/realm4/busyrp/modules/mod-npc-enchanter && git pull

    - name: update mod-playerbots
      shell: cd /realms/realm4/busyrp/modules/mod-playerbots && git pull

    - name: clean Build
      shell: rm -rf /realms/realm4/busyrp/build && mkdir /realms/realm4/busyrp/build

    - name: new Build
      shell: cd /realms/realm4/busyrp/build && cmake ../ -DCMAKE_INSTALL_PREFIX=/realms/realm4/busyrp/env/dist/ -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DWITH_WARNINGS=1 -DTOOLS_BUILD=all -DSCRIPTS=static -DMODULES=static

    - name: make Build
      shell: cd /realms/realm4/busyrp/build && make -j 8 && make install

    - name: Reboot
      reboot:
        reboot_timeout: 3600

    - name: Wait for reconnect
      wait_for_connection:
        connect_timeout: 10
        sleep: 5
        delay: 5
        timeout: 3600        