- hosts: realm1

  become: true
  tasks:
    - name: Update Realm1
      shell: cd /realms/realm1/azerothcore && git pull

    - name: update mod-autobalance
      shell: cd /realms/realm1/azerothcore/modules/mod-autobalance && git pull

    - name: update mod-individual-progression
      shell: cd /realms/realm1/azerothcore/modules/mod-individual-progression && git pull

    - name: update mod-npc-enchanter
      shell: cd /realms/realm1/azerothcore/modules/mod-npc-enchanter && git pull

    - name: update mod-ptr-template
      shell: cd /realms/realm1/azerothcore/modules/mod-ptr-template && git pull

    - name: clean Build
      shell: rm -rf /realms/realm1/azerothcore/build && mkdir /realms/realm1/azerothcore/build

    - name: new Build
      shell: cd /realms/realm1/azerothcore/build && cmake ../ -DCMAKE_INSTALL_PREFIX=/realms/realm1/azerothcore/env/dist/ -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DWITH_WARNINGS=1 -DTOOLS_BUILD=all -DSCRIPTS=static -DMODULES=static

    - name: make Build
      shell: cd /realms/realm1/azerothcore/build && make -j 8 && make install

    - name: Reboot
      reboot:
        reboot_timeout: 3600

    - name: Wait for reconnect
      wait_for_connection:
        connect_timeout: 10
        sleep: 5
        delay: 5
        timeout: 3600