- hosts: realm1

  become: true
  tasks:
    - name: Update realm1
      shell: cd /realms/realm1/azerothcore-wotlk && git pull

    - name: update mod-playerbots
      shell: cd /realms/realm1/azerothcore-wotlk/modules/mod-playerbots && git pull

    - name: clean Build
      shell: rm -rf /realms/realm1/azerothcore-wotlk/build && mkdir /realms/realm1/azerothcore-wotlk/build

    - name: new Build
      shell: cd /realms/realm1/azerothcore-wotlk/build && cmake ../ -DCMAKE_INSTALL_PREFIX=/realms/realm1/azerothcore-wotlk/env/dist/ -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DWITH_WARNINGS=1 -DTOOLS_BUILD=all -DSCRIPTS=static -DMODULES=static

    - name: make Build
      shell: cd /realms/realm1/azerothcore-wotlk/build && make -j 8 && make install

    - name: Reboot
      reboot:
        reboot_timeout: 3600

    - name: Wait for reconnect
      wait_for_connection:
        connect_timeout: 10
        sleep: 5
        delay: 5
        timeout: 3600